target  ?= romjudge
objects := $(patsubst %.c,%.o,$(wildcard *.c))
CFLAGS  += -Wall -Og -ggdb -std=c99
CC      := i686-w64-mingw64-gcc

.PHONY: all
all:	$(target)

.PHONY: clean
clean:
	rm -f $(target) $(objects)

$(target): $(objects)
